name: Blue-Green Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/charly15/blue-green-app:${{ github.ref_name }}
          file: app/Dockerfile
          context: ./app

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deployer/blue-green-app

            chmod +x scripts/*.sh
            chmod +x deploy/*.sh

            ACTIVE=$(scripts/status.sh)

            if [ "$ACTIVE" = "blue" ]; then
              TARGET="green"
              PORT=3002
            else
              TARGET="blue"
              PORT=3001
            fi

            echo "Entorno activo: $ACTIVE"
            echo "Desplegando en: $TARGET (puerto $PORT)"

            git fetch --all --tags
            git reset --hard ${{ github.ref_name }}

            ./deploy/deploy.sh $TARGET ${{ github.ref_name }}

            echo "Health check..."
            sleep 5

            if curl -s http://127.0.0.1:$PORT/ > /dev/null; then
              echo "✓ OK → Haciendo switch"
              ./scripts/switch.sh $TARGET
            else
              echo "✗ Falló → rollback"
              ./deploy/rollback.sh $TARGET
              exit 1
            fi
