name: Blue-Green Deployment

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/charly15/blue-green-app:${{ github.ref_name }}
          file: app/Dockerfile
          context: ./app

      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deployer/blue-green-app

            # Fix git issues
            git config --global --add safe.directory /home/deployer/blue-green-app
            sudo chown -R deployer:deployer /home/deployer/blue-green-app

            # Dar permisos a scripts
            chmod +x scripts/*.sh

            # Determinar entorno activo leyendo Nginx real
            ACTIVE=$(grep "server 127.0.0.1" /etc/nginx/sites-available/app | grep -o "300[01]")

            if [ "$ACTIVE" = "3000" ]; then
              DEPLOY_ENV="green"
              DEPLOY_PORT="3001"
            else
              DEPLOY_ENV="blue"
              DEPLOY_PORT="3000"
            fi

            echo "Activo actualmente: $ACTIVE"
            echo "Desplegando en: $DEPLOY_ENV ($DEPLOY_PORT)"

            # Pull Ãºltimo tag
            git fetch --all --tags
            git reset --hard origin/main

            # Detener contenedor previo (si existe)
            docker rm -f $DEPLOY_ENV || true

            # Ejecutar contenedor nuevo
            docker run -d \
              --name $DEPLOY_ENV \
              -p $DEPLOY_PORT:3000 \
              ghcr.io/charly15/blue-green-app:${{ github.ref_name }}

            # Actualizar Nginx al nuevo puerto
            sudo sed -i "s/server 127.0.0.1:300[01]/server 127.0.0.1:$DEPLOY_PORT/" /etc/nginx/sites-available/app

            sudo systemctl reload nginx

            echo "Switcheo completado. Online: $DEPLOY_ENV"
