name: Blue-Green Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/charly15/blue-green-app:${{ github.ref_name }}
          file: app/Dockerfile
          context: ./app

      - name: SSH Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/deployer/blue-green-app

            sudo git config --global --add safe.directory /home/deployer/blue-green-app
            sudo chown -R $USER:$USER /home/deployer/blue-green-app

            chmod +x scripts/*.sh || true
            chmod +x deploy/*.sh || true

            echo "✓ Permisos corregidos"

            # --- DETERMINAR ENTORNO ACTUAL Y SIGUIENTE ---
            ACTIVE=$(grep -A2 "upstream backend" /etc/nginx/sites-available/app | grep -o "300[12]" | head -n1)

            if [ "$ACTIVE" = "3001" ]; then
              DEPLOY_ENV="green"
              DEPLOY_PORT="3002"
            else
              DEPLOY_ENV="blue"
              DEPLOY_PORT="3001"
            fi

            echo "Backend actual: $ACTIVE"
            echo "Entorno destino:  $DEPLOY_ENV"
            echo "Puerto destino:   $DEPLOY_PORT"

            # --- ACTUALIZAR REPO ---
            git fetch --all --tags
            git reset --hard ${{ github.ref_name }}

            chmod +x scripts/*.sh || true
            chmod +x deploy/*.sh || true

            echo "✓ Permisos corregidos tras git reset"

            # --- DEPLOY ---
            ./deploy/deploy.sh $DEPLOY_ENV ${{ github.ref_name }}

            # Esperar contenedor para healthcheck
            sleep 5

            echo "Realizando health check..."
            if curl -s http://127.0.0.1:$DEPLOY_PORT/ > /dev/null 2>&1; then
              echo "✓ Health check exitoso"
              ./scripts/switch.sh $DEPLOY_ENV
              echo "✓ Switcheo realizado correctamente"
            else
              echo "✗ Health check fallido, revirtiendo..."
              ./deploy/rollback.sh $DEPLOY_ENV
              exit 1
            fi
